<?php

if (!is_user_logged_in()) {
  // User is not logged in, redirect to login page
  header("Location: /admin");
  exit();
}

$nav_home_admin = "Admin View All";
$selected_tag = isset($_GET['tag']) ? $_GET['tag'] : null;


$tags_message = false;
$query = "SELECT
movies.id AS 'movies.id',
movies.movie_name AS 'movies.movie_name',
movies.file_ext AS 'movies.file_ext',
movies.director AS 'movies.movie_director',
movies.release_year AS 'movies.release_year',
movies.genre AS 'movies.genre',
tags.tag AS 'tag'
FROM movies
JOIN movie_tags ON movies.id = movie_tags.movie_id
JOIN tags ON movie_tags.tag_id = tags.id";

if ($selected_tag) {
  if (is_numeric($selected_tag)) {

    $query = "SELECT * FROM movies WHERE release_year = :tag";
  } elseif (is_numeric($selected_tag)) {
      //  $selected_tag is a release yr
      $query = "SELECT * FROM movies WHERE id = :tag";
  } else {
      // $selected_tag is a genre
      $query = "SELECT movies.* FROM movies
                JOIN movie_tags ON movies.id = movie_tags.movie_id
                JOIN tags ON movie_tags.tag_id = tags.id
                WHERE tags.tag = :tag";
}
$params = [':tag' => $selected_tag];
$result = exec_sql_query($db, $query, $params);
} else {
  $result = exec_sql_query($db, 'SELECT * FROM movies ORDER BY movie_name ASC');
}

$records = $result->fetchAll();

if (empty($records)) {
  $tags_message = true;
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/public/styles/site.css">


  <title>CineFlix</title>
</head>

<body>

  <?php
  include("includes/header.php");
  ?>

  <h1> View All Movies</h1>

  <div class="container">

    <div class="tile-container">
      <?php foreach ($records as $record) :
        $file_url = "/public/uploads/movies/" . $record["id"] . "." . $record["file_ext"];
        ?>
          <div class="tile">
            <a href="/admin/movies/edit?<?php echo http_build_query(['id' => $record['id']]); ?>" class="tile-link">
              <div class=movie-cite>
                <img src="<?php echo htmlspecialchars($file_url); ?>" alt="<?php echo htmlspecialchars($record['file_ext']); ?>" class="movie-image">
              </div>
              <div class="tile-content">
                <h2><?php echo htmlspecialchars($record['movie_name']); ?></h2>
                <p><strong>Director:</strong> <?php echo htmlspecialchars($record['director']); ?></p>
                <p><strong>Release Year:</strong> <?php echo htmlspecialchars($record['release_year']); ?></p>
                <p><strong>Rating:</strong> <?php echo htmlspecialchars($record['rating']); ?></p>
                <p><strong>Genre:</strong> <?php echo htmlspecialchars($record['genre']); ?></p>
                <p><strong>Description:</strong> <?php echo htmlspecialchars($record['descript']); ?></p>
                <cite>Source: Generated by ChatGPT</cite>
              </div>
            </a>
            <div class="edit-link-container">
              <a href="/admin/movies/edit?<?php echo http_build_query(['id' => $record['id']]); ?>">Edit Entry</a>
            </div>
          </div>
      <?php endforeach; ?>
  </div>
  <div class="admin-tags-filter">
    <h2>Filter Movie by Tag</h2>


    <?php
    // Query to fetch all tags from the database
    $query = "SELECT tag FROM tags ORDER BY tag";
    $result = exec_sql_query($db, $query);

    if ($result) {
      $tags = $result->fetchAll(PDO::FETCH_COLUMN, 0);
      foreach ($tags as $tag):
          $url = "/admin/movies?" . http_build_query(['tag' => $tag]);
      ?>
        <a href="<?php echo htmlspecialchars($url); ?>">
            <?php echo htmlspecialchars($tag); ?>
        </a>
      <?php endforeach;
      }
      ?>

  </div>

  <?php if ($tags_message) { ?>
    <div class= "no-tags">
      <p>There are no movies found in this tag.</p>
    </div>
  <?php } ?>


  </div>
  <?php
    include("includes/footer.php");
  ?>
</body>

</html>
