<?php

$nav_home_consumer = "active_page";

$selected_tag = isset($_GET['tag']) ? $_GET['tag'] : null;

$tags_message = false;


$query = "SELECT
movies.id AS 'movies.id',
movies.movie_name AS 'movie_name',
movies.file_ext AS 'file_ext',
movies.director AS 'movie_director',
movies.release_year AS 'release_year',
movies.genre AS 'genre',
tags.tag AS 'tag'
FROM movies
JOIN movie_tags ON movies.id = movie_tags.movie_id
JOIN tags ON movie_tags.tag_id = tags.id";

$page_title = 'Consumer View All';

// if ($selected_tag) {
//     if (is_numeric($selected_tag)) { // it's a year
//         $query .= "WHERE movies.release_year = :selected_tag";
//     } else { // It's a genre
//       $query .= " WHERE tags.tag = :selected_tag";
//     }
//     $params = [':selected_tag' => $selected_tag];
//     $result = exec_sql_query($db, $query, $params);
// } else {
//   $result = exec_sql_query($db, 'SELECT * FROM movies');
// }
if ($selected_tag) {
  if (is_numeric($selected_tag)) {

    $query = "SELECT * FROM movies WHERE release_year = :tag";
  } elseif (is_numeric($selected_tag)) {
      //  $selected_tag is a release yr
      $query = "SELECT * FROM movies WHERE id = :tag";
  } else {
      // $selected_tag is a genre
      $query = "SELECT movies.* FROM movies
                JOIN movie_tags ON movies.id = movie_tags.movie_id
                JOIN tags ON movie_tags.tag_id = tags.id
                WHERE tags.tag = :tag";
}
$params = [':tag' => $selected_tag];
$result = exec_sql_query($db, $query, $params);
} else {
  $result = exec_sql_query($db, 'SELECT * FROM movies ORDER BY movie_name ASC');
}

$records = $result->fetchAll();

if (empty($records)) {
  $tags_message = true;
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/public/styles/site.css">


  <title>CineFlix</title>
</head>

<body>

  <?php
  include("includes/header.php");
  ?>

  <h1> <?php
  // Check if a tag is selected and display it as part of the title
  echo isset($selected_tag) && !empty($selected_tag) ? ' ' . htmlspecialchars($selected_tag) : 'View All Movies';

  ?>  </h1>

  <div class="container">

  <div class="card-container">
    <?php foreach ($records as $record) :
            $file_url = "/public/uploads/movies/" . $record["id"] . "." . $record["file_ext"];
            ?>
      <div class="card">
        <a href="/movie-details?<?php echo http_build_query (array(
                                              "id" => $record['id']
                                            )) ?>" class="card-page">Click for Movie Details
          <figure>
            <img src="<?php echo htmlspecialchars($file_url); ?>" alt="movie poster">
            <figcaption>Source: IMDb</figcaption>
          </figure>
        </a>
        <a href="https://www.imdb.com/" class="movie-img">Visit IMDb</a>

        <div class="card-content">
        <a href="/movie-details?<?php echo http_build_query (array(
                                              "id" => $record['id']
                                            )) ?>" class="card-page">
          <h2 class="card-title"><?php echo htmlspecialchars($record['movie_name']); ?></h2>
          <p class="card-details">Release Year: <?php echo htmlspecialchars($record['release_year']); ?></p>
          <p class="card-details">Genre: <?php echo htmlspecialchars($record['genre']); ?></p>
          <cite>Source: Generated by ChatGPT</cite>
          </a>
        </div>
      </div>
      <?php endforeach; ?>
  </div>

  <div class="consumer-tags-filter">
    <h2 class="filter-title">Filter Movie by Tag</h2>


    <?php
    // Query to fetch all tags from the database
    $query = "SELECT tag FROM tags ORDER BY tag";
    $result = exec_sql_query($db, $query);

    if ($result) {
      $tags = $result->fetchAll(PDO::FETCH_COLUMN, 0);
      foreach ($tags as $tag):
          $url = "/?" . http_build_query(['tag' => $tag]);
      ?>
        <a href="<?php echo htmlspecialchars($url); ?>">
            <?php echo htmlspecialchars($tag); ?>
        </a>
      <?php endforeach;
      }
      ?>

  </div>

  <?php if ($tags_message) { ?>
  <div class= "no-tags">
    <p>There are no movies found in this tag.</p>
  </div>
  <?php } ?>
  </div>


  <?php
  include("includes/footer.php");
  ?>

</body>

</html>
