<?php
define("MAX_FILE_SIZE", 1000000);

if (isset($_POST["request"])) {

  $upload = $_FILES["image"];
  $movie_image = "jpg";
  $movie_title = htmlspecialchars($_POST["title"]);
  $movie_director = htmlspecialchars($_POST["director"]);
  $movie_year = htmlspecialchars($_POST["year"]);
  $movie_genre = htmlspecialchars($_POST["genre"]);
  $movie_rating = htmlspecialchars($_POST["rating"]);
  $movie_description = htmlspecialchars($_POST["description"]);


  $form_valid = true;
}


if ($form_valid) {
  // insert upload into DB

// get the info about the uploaded files.
  $upload_file_ext = ".jpg";
  $upload_movie_name = "hello";
  $result = exec_sql_query(
    $db,
    "INSERT INTO movies (id, file_ext, movie_name, director, release_year, genre, rating, descript) VALUES (:id, :file_ext, :movie_name, :director, :release_year, :genre, :rating, :descript)",
    array(
      ":id" => $upload_id,
      ":file_ext" => $movie_image,
      ":movie_name" => $movie_title,
      ":director" => $movie_director,
      ":release_year" => $movie_year,
      ":genre" => $movie_genre,
      ":rating" => $movie_rating,
      ":descript" => $movie_description
    )
  );

  if ($result) {
    // moving uploaded file to uploads folder
    $record_id = $db->lastInsertId("id");

    $upload_storage_path = "public/uploads/movies/" . $record_id . $upload_file_ext;

    if (move_uploaded_file($upload["tmp_name"], $upload_storage_path) == false) {
      error_log("Failed to permanently store the uploaded file on the file server. Please check that the server folder exists.");
    }
  }
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/public/styles/site.css">


  <title>CineFlix</title>
</head>

<body>

  <?php
  include("includes/header.php");
  ?>

<div class="form-header">
    <h2>Movie Submission Form</h2>

    <p>Add Your Favorite Movie to Our Catalog!</p>
    <p>Share the magic of your favorite film with our community! Use the form below to submit details about the movie you love. Whether it's a blockbuster hit or a hidden indie gem, let others discover and enjoy the masterpiece through your recommendation. Fill out the form now and help us grow our diverse movie catalog!

      <cite>Source: Generated by ChatGPT</cite>
    </p>
    </div>

    <form id="request-form" action="/add-movies" method="post" enctype="multipart/form-data" novalidate>

     <!-- MAX_FILE_SIZE -->
     <input type="hidden" name="MAX_FILE_SIZE" value="<?php echo MAX_FILE_SIZE; ?>">

      <div class="label">
          <label for="file-request">&#42; JPG File:</label>
          <input id="file-request" type="file" name="image" accept=".jpg,image/jpg">
      </div>

      <div class="label">
        <label for="title-request">&#42; Movie Title:</label>
        <input type="text" name="title" id="title-request">
      </div>

      <div class="label">
        <label for="director-request">&#42; Director:</label>
        <input type="text" name="director" id="director-request">
      </div>

      <div class="label">
        <label for="year-request">&#42; Release Year:</label>
        <select name="year" id="year-request">
          <option disabled selected value> -- select an option -- </option>
          <option value="2010">2010</option>
          <option value="2011">2011</option>
          <option value="2012">2012</option>
          <option value="2013">2013</option>
          <option value="2014">2014</option>
          <option value="2015">2015</option>
          <option value="2016">2016</option>
          <option value="2017">2017</option>
          <option value="2018">2018</option>
          <option value="2019">2019</option>
          <option value="2020">2020</option>
        </select>
      </div>

      <div class="label">
        <label for="genre-request">&#42; Genre:</label>
        <select name="genre" id="genre-request">
          <option disabled selected value> -- select an option -- </option>
          <option value="Thriller">Thriller</option>
          <option value="Action">Action</option>
          <option value="Drama">Drama</option>
          <option value="Romance">Romance</option>
          <option value="Science Fiction">Science Fiction</option>
          <option value="Comedy">Comedy</option>
          <option value="Crime">Crime</option>
        </select>
      </div>

      <div class="label">
        <label for="rating-request">&#42; Rating (1-5):</label>
        <input type="text" name="rating" id="rating-request" value=" <?php echo htmlspecialchars($movie_details['rating']); ?>" />
      </div>

      <div class="label">
        <label for="description-request">&#42; Description:</label>
        <input type="text" name="description" id="description-request" value="<?php echo htmlspecialchars($movie_details['descript']); ?>" />
      </div>

      <div class="submit-button">
        <button id="request-info" type="submit" name="request">Submit Form </button>

      </div>

    </form>

    <?php
  include("includes/footer.php");
  ?>

</body>

</html>
