<?php

// Assuming exec_sql_query is a function that prepares, binds, and executes SQL queries,
// and then returns the fetched result.

$movie_id = $_GET['id'] ?? NULL;

if ($movie_id) {
    // Fetch the main details of the movie
    $movie_query = "SELECT
                        id,
                        movie_name,
                        file_ext,
                        director,
                        release_year,
                        genre,
                        rating,
                        descript
                    FROM movies
                    WHERE id = :movie_id";

    $movie_details = exec_sql_query($db, $movie_query, array(":movie_id" => $movie_id))->fetchAll();
    $movie_detail = $movie_details[0] ?? null;


    $tags_query = "SELECT tags.tag
                   FROM tags
                   INNER JOIN movie_tags ON tags.id = movie_tags.tag_id
                   WHERE movie_tags.movie_id = :id";

    // get tags
    $tags = exec_sql_query($db, $tags_query, array(":id"=>$movie_id ))->fetchAll();
} else {
}

if ($movie_detail) {
  $file_url = "public/uploads/movies/" . $movie_detail['id'] . "." . $movie_detail['file_ext'];

}

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/public/styles/site.css">

  <title><?php echo htmlspecialchars($movie_detail['movie_name']); ?> - Movie Details</title>
</head>

<body>

  <?php
  include("includes/header.php");
  ?>

  <div class="button"><a href="/" class="goback">&lt; Go Back</a></div>

  <div class="content-container">

    <div class="img-container">
    <figure>
    <img src="<?php echo htmlspecialchars($file_url); ?>" alt="movie poster" class="poster-image">
    <figcaption class= "img-cite"><a href="https://www.123rf.com/photo_30404493_stamp-with-word-movies-inside-vector-illustration.html">Source: 123rf</a></figcaption>
    </figure>
    </div>

    <div class="details-container">
    <h1><?php echo htmlspecialchars($movie_detail['movie_name']); ?></h1>
      <p><strong>Director:</strong> <?php echo htmlspecialchars($movie_detail['director']); ?></p>
      <p><strong>Release Year:</strong> <?php echo htmlspecialchars($movie_detail['release_year']); ?></p>
      <p><strong>Genre:</strong> <?php echo htmlspecialchars($movie_detail['genre']); ?></p>
      <p><strong>Rating:</strong> <?php echo htmlspecialchars($movie_detail['rating']); ?></p>
      <p><strong>Description:</strong> <?php echo htmlspecialchars($movie_detail['descript']); ?></p>
      <?php
          foreach ($tags as $tag) {
            echo '<div class="tag">' . htmlspecialchars($tag['tag']) . '</div> ';
          }
      ?>
    <cite>Source: Generated by ChatGPT</cite>
    </div>

  </div>

  <?php
  include("includes/footer.php");
  ?>

</body>

</html>
