<header>

  <div class="title">
    <h1>CineFlix</h1>

    <h2>Your Ultimate Movie Pub</h2>

    <cite>Source: Generated by ChatGPT</cite>
  </div>
  <nav>
    <ul>
        <li class="<?php echo $nav_home_consumer; ?>"><a href="/">View All Movies</a></li>
        <li class="<?php echo $nav_add_movies; ?>"><a href="/add-movies">Add Movies</a></li>

      <?php if (is_user_logged_in()) { ?>
      <li class="<?php echo $nav_home_admin; ?>"><a href="/admin/movies">Admin View All</a></li>
        <li class="float-right"><a class="sign-out" href="<?php echo logout_url(); ?>">Sign Out</a></li>
      <?php } ?>
    </ul>
  </nav>

</header>
